### ISSUE TITLE
Broken uption use_vis2=none?

### ISSUE THREAD

**Issue by bufeo** [emmt/MiRA#12]
The command line option -use_vis2 seems to have no effect on the data considered for imaging. Whether set to 'none' or 'all' the code always reports a line similar to the following
 "INFO - will fit 67 OI_VIS2 data"

**Comment by emmt** [comment]
Thanks for reporting this bug. It should be fixed now (see commit https://github.com/emmt/MiRA/commit/ad5df266d77a96d7e566c2f0480386574f00d2c3).

**Comment by bufeo** [comment]
Thank you! Now it works.

**Comment by emmt** [comment]
Fine!
